[package]
name = "konnektoren-bevy"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.16.1" }
bevy_egui = "0.34.1"

[features]
default = ["theme", "ui"]
theme = []
ui = ["theme"]
