[package]
name = "konnektoren-bevy-demo"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "demo"
path = "src/main.rs"

[dependencies]
konnektoren-bevy = { path = ".." }
bevy = { version = "0.16.1", features = ["dynamic_linking"] }
bevy_egui = "0.34.1"
