[package]
name = "konnektoren-bevy-demo"
version = "0.2.0"
edition = "2021"

[[bin]]
name = "demo"
path = "src/main.rs"

[dependencies]
konnektoren-bevy = { path = ".." }
bevy = { workspace = true }
bevy_egui = { workspace = true }
wasm-bindgen = { workspace = true }
