name: Build and Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pkg-config \
            libasound2-dev \
            libudev-dev \
            libxkbcommon-dev \
            libwayland-dev \
            libxrandr-dev \
            libxcursor-dev \
            libxi-dev \
            libxinerama-dev \
            libgl1-mesa-dev

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            . -> target
            demo -> target

      - name: Install trunk
        uses: jetli/trunk-action@v0.5.0
        with:
          version: "latest"

      - name: Build main library
        run: cargo build --release

      - name: Build WASM demo with trunk
        run: |
          cd demo
          trunk build --release --public-url /konnektoren-bevy/

      - name: Build docs
        run: cargo doc --workspace --no-deps

      - name: Prepare GitHub Pages files
        run: |
          cd demo/dist
          # Create .nojekyll to bypass Jekyll processing
          touch .nojekyll
          # Ensure 404.html exists for SPA routing
          cp index.html 404.html
          # Copy docs to subfolder
          mkdir -p docs
          cp -r ../../target/doc/* docs/
          # Add link to docs in index.html
          echo '<div style="position: fixed; top: 10px; right: 10px; z-index: 1000;"><a href="docs/konnektoren_bevy/index.html" style="background: #ff8c00; color: white; padding: 8px 16px; text-decoration: none; border-radius: 4px;">📚 API Docs</a></div>' >> index.html

      - name: Debug build output
        run: |
          echo "=== Demo Build Debug ==="
          ls -la demo/dist/
          echo "=== Assets folder ==="
          ls -la demo/dist/assets/ || echo "No assets folder"
          echo "=== Docs folder ==="
          ls -la demo/dist/docs/ | head -10 || echo "No docs folder"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./demo/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
